### ISSUE TITLE
How to change administrator user role

### ISSUE THREAD

**Issue by MrFloffy** [sipwise/ngcp-admin-ui#44]
I just did a fresh installation of sipwise on version 11.5.1, but when I log in with the default administrator user it is assigned the "reseller" role and I can't configure things like peerings, etc. Does anyone know how to solve it? Thanks!

**Comment by linuxmaniac** [comment]
You should direct your question at
https://lists.sipwise.com/mailman/listinfo/spce-user_lists.sipwise.com

**Comment by MrFloffy** [comment]
Apparently it was a bug or installation error, I reinstalled and it was fixed.
